language: python
python:
  - "3.6.2"
# command to install dependencies
install: 
  - "pip install requests coveralls nose-htmloutput nose coverage"
# Commented as failing  - "pip install -U wxpython"
script: nosetests -v --with-id  --with-coverage --with-html --cover-package=./

after_success:  
  - coveralls 