language: python
python:
  - "3.6.2"
# command to install dependencies
install: "pip install requests coveralls"
script: coverage run --branch --source=. -m unittest discover -v

after_success:  
  - coveralls 